/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */
#include "vtk_proxy.h"

void _wrap_free_output_cstr(char * carg1);
const char * _wrap_vtkObjectBase_GetClassName(SwigObj * carg1);
int _wrap_vtkObjectBase_IsA(vtkObjectBase * carg1, char const * carg2);
void _wrap_vtkObjectBase_Delete(vtkObjectBase * carg1);
void _wrap_vtkObjectBase_Print(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkObjectBase_Register(vtkObjectBase * carg1, SwigObj * carg2);
void _wrap_vtkObjectBase_UnRegister(vtkObjectBase * carg1, SwigObj * carg2);
/*aaaaaa*/SwigObj * _wrap_vtkObjectBase_New();
int _wrap_vtkObjectBase_IsTypeOf(char const * carg1);
char * _wrap_vtkObjectBase_ToString(SwigObj * carg1);
/*aaaaaa*/SwigObj * _wrap_vtkObject_NewInstance(SwigObj * carg1);
bool _wrap_vtkObject_GetDebug(SwigObj * carg1);
void _wrap_vtkObject_SetDebug(SwigObj * carg1, bool carg2);
const char * _wrap_vtkObject_GetClassName(SwigObj * carg1);
int _wrap_vtkObject_IsA(SwigObj * carg1, char const * carg2);
void _wrap_vtkObject_Delete(SwigObj * carg1);
void _wrap_vtkObject_Print(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkObject_Register(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkObject_UnRegister(SwigObj * carg1, SwigObj * carg2);
/*aaaaaa*/SwigObj * _wrap_vtkAlgorithm_GetOutputPort(SwigObj * carg1);
/*aaaaaa*/SwigObj * _wrap_vtkAlgorithm_NewInstance(SwigObj * carg1);
bool _wrap_vtkAlgorithm_GetDebug(SwigObj * carg1);
void _wrap_vtkAlgorithm_SetDebug(SwigObj * carg1, bool carg2);
const char * _wrap_vtkAlgorithm_GetClassName(SwigObj * carg1);
int _wrap_vtkAlgorithm_IsA(SwigObj * carg1, char const * carg2);
void _wrap_vtkAlgorithm_Delete(SwigObj * carg1);
void _wrap_vtkAlgorithm_Print(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkAlgorithm_Register(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkAlgorithm_UnRegister(SwigObj * carg1, SwigObj * carg2);
/*aaaaaa*/SwigObj * _wrap_vtkPolyDataAlgorithm_GetOutputPort(SwigObj * carg1);
/*aaaaaa*/SwigObj * _wrap_vtkPolyDataAlgorithm_NewInstance(SwigObj * carg1);
bool _wrap_vtkPolyDataAlgorithm_GetDebug(SwigObj * carg1);
void _wrap_vtkPolyDataAlgorithm_SetDebug(SwigObj * carg1, bool carg2);
const char * _wrap_vtkPolyDataAlgorithm_GetClassName(SwigObj * carg1);
int _wrap_vtkPolyDataAlgorithm_IsA(SwigObj * carg1, char const * carg2);
void _wrap_vtkPolyDataAlgorithm_Delete(SwigObj * carg1);
void _wrap_vtkPolyDataAlgorithm_Print(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkPolyDataAlgorithm_Register(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkPolyDataAlgorithm_UnRegister(SwigObj * carg1, SwigObj * carg2);
/*aaaaaa*/SwigObj * _wrap_vtkPolyDataMapper_New();
void _wrap_vtkPolyDataMapper_Delete(vtkPolyDataMapper * carg1);
void _wrap_vtkPolyDataMapper_SetInputConnection(vtkPolyDataMapper * carg1, SwigObj * carg2);
/*aaaaaa*/SwigObj * _wrap_vtkPolyDataMapper_GetOutputPort(SwigObj * carg1);
/*aaaaaa*/SwigObj * _wrap_vtkPolyDataMapper_NewInstance(SwigObj * carg1);
bool _wrap_vtkPolyDataMapper_GetDebug(SwigObj * carg1);
void _wrap_vtkPolyDataMapper_SetDebug(SwigObj * carg1, bool carg2);
const char * _wrap_vtkPolyDataMapper_GetClassName(SwigObj * carg1);
int _wrap_vtkPolyDataMapper_IsA(SwigObj * carg1, char const * carg2);
void _wrap_vtkPolyDataMapper_Print(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkPolyDataMapper_Register(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkPolyDataMapper_UnRegister(SwigObj * carg1, SwigObj * carg2);
/*aaaaaa*/SwigObj * _wrap_vtkActor_New();
void _wrap_vtkActor_Delete(vtkActor * carg1);
void _wrap_vtkActor_SetMapper(vtkActor * carg1, SwigObj * carg2);
/*aaaaaa*/SwigObj * _wrap_vtkActor_NewInstance(SwigObj * carg1);
bool _wrap_vtkActor_GetDebug(SwigObj * carg1);
void _wrap_vtkActor_SetDebug(SwigObj * carg1, bool carg2);
const char * _wrap_vtkActor_GetClassName(SwigObj * carg1);
int _wrap_vtkActor_IsA(SwigObj * carg1, char const * carg2);
void _wrap_vtkActor_Print(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkActor_Register(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkActor_UnRegister(SwigObj * carg1, SwigObj * carg2);
/*aaaaaa*/SwigObj * _wrap_vtkConeSource_New();
void _wrap_vtkConeSource_Delete(vtkConeSource * carg1);
void _wrap_vtkConeSource_SetHeight(SwigObj * carg1, double carg2);
double _wrap_vtkConeSource_GetHeight(SwigObj * carg1);
void _wrap_vtkConeSource_SetRadius(SwigObj * carg1, double carg2);
double _wrap_vtkConeSource_GetRadius(SwigObj * carg1);
void _wrap_vtkConeSource_SetResolution(SwigObj * carg1, int carg2);
int _wrap_vtkConeSource_GetResolution(SwigObj * carg1);
void _wrap_vtkConeSource_SetCenter(SwigObj * carg1, double carg2, double carg3, double carg4);
double * _wrap_vtkConeSource_GetCenter_pvtkConeSource(SwigObj * carg1);
void _wrap_vtkConeSource_GetCenter_pvtkConeSource_a3d(SwigObj * carg1, /*aaa*/ double * carg2);
void _wrap_vtkConeSource_SetDirection(SwigObj * carg1, double carg2, double carg3, double carg4);
double * _wrap_vtkConeSource_GetDirection(SwigObj * carg1);
void _wrap_vtkConeSource_SetAngle(SwigObj * carg1, double carg2);
double _wrap_vtkConeSource_GetAngle(SwigObj * carg1);
/*aaaaaa*/SwigObj * _wrap_vtkConeSource_GetOutputPort(SwigObj * carg1);
/*aaaaaa*/SwigObj * _wrap_vtkConeSource_NewInstance(SwigObj * carg1);
bool _wrap_vtkConeSource_GetDebug(SwigObj * carg1);
void _wrap_vtkConeSource_SetDebug(SwigObj * carg1, bool carg2);
const char * _wrap_vtkConeSource_GetClassName(SwigObj * carg1);
int _wrap_vtkConeSource_IsA(SwigObj * carg1, char const * carg2);
void _wrap_vtkConeSource_Print(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkConeSource_Register(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkConeSource_UnRegister(SwigObj * carg1, SwigObj * carg2);
/*aaaaaa*/SwigObj * _wrap_vtkRenderer_New();
void _wrap_vtkRenderer_Delete(SwigObj * carg1);
void _wrap_vtkRenderer_AddActor(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkRenderer_SetBackground(SwigObj * carg1, double carg2, double carg3, double carg4);
void _wrap_vtkRenderer_SetBackground2(SwigObj * carg1, double carg2, double carg3, double carg4);
void _wrap_vtkRenderer_SetGradientBackground(SwigObj * carg1, bool carg2);
/*aaaaaa*/SwigObj * _wrap_vtkRenderWindow_New();
void _wrap_vtkRenderWindow_Delete(SwigObj * carg1);
void _wrap_vtkRenderWindow_AddRenderer(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkRenderWindow_SetSize(SwigObj * carg1, int carg2, int carg3);
/*aaaaaa*/SwigObj * _wrap_vtkRenderWindowInteractor_New();
void _wrap_vtkRenderWindowInteractor_Delete(SwigObj * carg1);
void _wrap_vtkRenderWindowInteractor_SetRenderWindow(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkRenderWindowInteractor_Initialize(SwigObj * carg1);
void _wrap_vtkRenderWindowInteractor_Start(SwigObj * carg1);
void _wrap_vtkRenderWindowInteractor_SetInteractorStyle(vtkRenderWindowInteractor * carg1, SwigObj * carg2);
/*aaaaaa*/SwigObj * _wrap_vtkRenderWindowInteractor_GetInteractorStyle(vtkRenderWindowInteractor * carg1);
/*aaaaaa*/SwigObj * _wrap_vtkInteractorStyleTrackballCamera_New();
void _wrap_vtkInteractorStyleTrackballCamera_Delete(SwigObj * carg1);
/*aaaaaa*/SwigObj * _wrap_vtkBoxWidget_New();
void _wrap_vtkBoxWidget_Delete(SwigObj * carg1);
void _wrap_vtkBoxWidget_SetInteractor(vtkBoxWidget * carg1, SwigObj * carg2);
/*aaaaaa*/SwigObj * _wrap_vtkBoxWidget_GetInteractor(vtkBoxWidget * carg1);
void _wrap_vtkBoxWidget_PlaceWidget(SwigObj * carg1);
void _wrap_vtkBoxWidget_SetPlaceFactor(vtkBoxWidget * carg1, double carg2);
double _wrap_vtkBoxWidget_GetPlaceFactor(vtkBoxWidget * carg1);
void _wrap_vtkBoxWidget_SetProp3D(vtkBoxWidget * carg1, SwigObj * carg2);
/*aaaaaa*/SwigObj * _wrap_vtkBoxWidget_GetProp3D(vtkBoxWidget * carg1);
void _wrap_vtkBoxWidget_On(SwigObj * carg1);
void _wrap_vtkBoxWidget_Off(SwigObj * carg1);

void free_output_cstr(char * carg1) {
  return _wrap_free_output_cstr(carg1);
}
const char * vtkObjectBase_GetClassName(SwigObj * carg1) {
  return _wrap_vtkObjectBase_GetClassName(carg1);
}
int vtkObjectBase_IsA(vtkObjectBase * carg1, char const * carg2) {
  return _wrap_vtkObjectBase_IsA(carg1, carg2);
}
void vtkObjectBase_Delete(vtkObjectBase * carg1) {
  return _wrap_vtkObjectBase_Delete(carg1);
}
void vtkObjectBase_Print(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkObjectBase_Print(carg1, carg2);
}
void vtkObjectBase_Register(vtkObjectBase * carg1, SwigObj * carg2) {
  return _wrap_vtkObjectBase_Register(carg1, carg2);
}
void vtkObjectBase_UnRegister(vtkObjectBase * carg1, SwigObj * carg2) {
  return _wrap_vtkObjectBase_UnRegister(carg1, carg2);
}
/*aaaaaa*/SwigObj * vtkObjectBase_New() {
  return _wrap_vtkObjectBase_New();
}
int vtkObjectBase_IsTypeOf(char const * carg1) {
  return _wrap_vtkObjectBase_IsTypeOf(carg1);
}
char * vtkObjectBase_ToString(SwigObj * carg1) {
  return _wrap_vtkObjectBase_ToString(carg1);
}
/*aaaaaa*/SwigObj * vtkObject_NewInstance(SwigObj * carg1) {
  return _wrap_vtkObject_NewInstance(carg1);
}
bool vtkObject_GetDebug(SwigObj * carg1) {
  return _wrap_vtkObject_GetDebug(carg1);
}
void vtkObject_SetDebug(SwigObj * carg1, bool carg2) {
  return _wrap_vtkObject_SetDebug(carg1, carg2);
}
const char * vtkObject_GetClassName(SwigObj * carg1) {
  return _wrap_vtkObject_GetClassName(carg1);
}
int vtkObject_IsA(SwigObj * carg1, char const * carg2) {
  return _wrap_vtkObject_IsA(carg1, carg2);
}
void vtkObject_Delete(SwigObj * carg1) {
  return _wrap_vtkObject_Delete(carg1);
}
void vtkObject_Print(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkObject_Print(carg1, carg2);
}
void vtkObject_Register(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkObject_Register(carg1, carg2);
}
void vtkObject_UnRegister(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkObject_UnRegister(carg1, carg2);
}
/*aaaaaa*/SwigObj * vtkAlgorithm_GetOutputPort(SwigObj * carg1) {
  return _wrap_vtkAlgorithm_GetOutputPort(carg1);
}
/*aaaaaa*/SwigObj * vtkAlgorithm_NewInstance(SwigObj * carg1) {
  return _wrap_vtkAlgorithm_NewInstance(carg1);
}
bool vtkAlgorithm_GetDebug(SwigObj * carg1) {
  return _wrap_vtkAlgorithm_GetDebug(carg1);
}
void vtkAlgorithm_SetDebug(SwigObj * carg1, bool carg2) {
  return _wrap_vtkAlgorithm_SetDebug(carg1, carg2);
}
const char * vtkAlgorithm_GetClassName(SwigObj * carg1) {
  return _wrap_vtkAlgorithm_GetClassName(carg1);
}
int vtkAlgorithm_IsA(SwigObj * carg1, char const * carg2) {
  return _wrap_vtkAlgorithm_IsA(carg1, carg2);
}
void vtkAlgorithm_Delete(SwigObj * carg1) {
  return _wrap_vtkAlgorithm_Delete(carg1);
}
void vtkAlgorithm_Print(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkAlgorithm_Print(carg1, carg2);
}
void vtkAlgorithm_Register(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkAlgorithm_Register(carg1, carg2);
}
void vtkAlgorithm_UnRegister(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkAlgorithm_UnRegister(carg1, carg2);
}
/*aaaaaa*/SwigObj * vtkPolyDataAlgorithm_GetOutputPort(SwigObj * carg1) {
  return _wrap_vtkPolyDataAlgorithm_GetOutputPort(carg1);
}
/*aaaaaa*/SwigObj * vtkPolyDataAlgorithm_NewInstance(SwigObj * carg1) {
  return _wrap_vtkPolyDataAlgorithm_NewInstance(carg1);
}
bool vtkPolyDataAlgorithm_GetDebug(SwigObj * carg1) {
  return _wrap_vtkPolyDataAlgorithm_GetDebug(carg1);
}
void vtkPolyDataAlgorithm_SetDebug(SwigObj * carg1, bool carg2) {
  return _wrap_vtkPolyDataAlgorithm_SetDebug(carg1, carg2);
}
const char * vtkPolyDataAlgorithm_GetClassName(SwigObj * carg1) {
  return _wrap_vtkPolyDataAlgorithm_GetClassName(carg1);
}
int vtkPolyDataAlgorithm_IsA(SwigObj * carg1, char const * carg2) {
  return _wrap_vtkPolyDataAlgorithm_IsA(carg1, carg2);
}
void vtkPolyDataAlgorithm_Delete(SwigObj * carg1) {
  return _wrap_vtkPolyDataAlgorithm_Delete(carg1);
}
void vtkPolyDataAlgorithm_Print(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkPolyDataAlgorithm_Print(carg1, carg2);
}
void vtkPolyDataAlgorithm_Register(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkPolyDataAlgorithm_Register(carg1, carg2);
}
void vtkPolyDataAlgorithm_UnRegister(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkPolyDataAlgorithm_UnRegister(carg1, carg2);
}
/*aaaaaa*/SwigObj * vtkPolyDataMapper_New() {
  return _wrap_vtkPolyDataMapper_New();
}
void vtkPolyDataMapper_Delete(vtkPolyDataMapper * carg1) {
  return _wrap_vtkPolyDataMapper_Delete(carg1);
}
void vtkPolyDataMapper_SetInputConnection(vtkPolyDataMapper * carg1, SwigObj * carg2) {
  return _wrap_vtkPolyDataMapper_SetInputConnection(carg1, carg2);
}
/*aaaaaa*/SwigObj * vtkPolyDataMapper_GetOutputPort(SwigObj * carg1) {
  return _wrap_vtkPolyDataMapper_GetOutputPort(carg1);
}
/*aaaaaa*/SwigObj * vtkPolyDataMapper_NewInstance(SwigObj * carg1) {
  return _wrap_vtkPolyDataMapper_NewInstance(carg1);
}
bool vtkPolyDataMapper_GetDebug(SwigObj * carg1) {
  return _wrap_vtkPolyDataMapper_GetDebug(carg1);
}
void vtkPolyDataMapper_SetDebug(SwigObj * carg1, bool carg2) {
  return _wrap_vtkPolyDataMapper_SetDebug(carg1, carg2);
}
const char * vtkPolyDataMapper_GetClassName(SwigObj * carg1) {
  return _wrap_vtkPolyDataMapper_GetClassName(carg1);
}
int vtkPolyDataMapper_IsA(SwigObj * carg1, char const * carg2) {
  return _wrap_vtkPolyDataMapper_IsA(carg1, carg2);
}
void vtkPolyDataMapper_Print(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkPolyDataMapper_Print(carg1, carg2);
}
void vtkPolyDataMapper_Register(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkPolyDataMapper_Register(carg1, carg2);
}
void vtkPolyDataMapper_UnRegister(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkPolyDataMapper_UnRegister(carg1, carg2);
}
/*aaaaaa*/SwigObj * vtkActor_New() {
  return _wrap_vtkActor_New();
}
void vtkActor_Delete(vtkActor * carg1) {
  return _wrap_vtkActor_Delete(carg1);
}
void vtkActor_SetMapper(vtkActor * carg1, SwigObj * carg2) {
  return _wrap_vtkActor_SetMapper(carg1, carg2);
}
/*aaaaaa*/SwigObj * vtkActor_NewInstance(SwigObj * carg1) {
  return _wrap_vtkActor_NewInstance(carg1);
}
bool vtkActor_GetDebug(SwigObj * carg1) {
  return _wrap_vtkActor_GetDebug(carg1);
}
void vtkActor_SetDebug(SwigObj * carg1, bool carg2) {
  return _wrap_vtkActor_SetDebug(carg1, carg2);
}
const char * vtkActor_GetClassName(SwigObj * carg1) {
  return _wrap_vtkActor_GetClassName(carg1);
}
int vtkActor_IsA(SwigObj * carg1, char const * carg2) {
  return _wrap_vtkActor_IsA(carg1, carg2);
}
void vtkActor_Print(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkActor_Print(carg1, carg2);
}
void vtkActor_Register(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkActor_Register(carg1, carg2);
}
void vtkActor_UnRegister(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkActor_UnRegister(carg1, carg2);
}
/*aaaaaa*/SwigObj * vtkConeSource_New() {
  return _wrap_vtkConeSource_New();
}
void vtkConeSource_Delete(vtkConeSource * carg1) {
  return _wrap_vtkConeSource_Delete(carg1);
}
void vtkConeSource_SetHeight(SwigObj * carg1, double carg2) {
  return _wrap_vtkConeSource_SetHeight(carg1, carg2);
}
double vtkConeSource_GetHeight(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetHeight(carg1);
}
void vtkConeSource_SetRadius(SwigObj * carg1, double carg2) {
  return _wrap_vtkConeSource_SetRadius(carg1, carg2);
}
double vtkConeSource_GetRadius(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetRadius(carg1);
}
void vtkConeSource_SetResolution(SwigObj * carg1, int carg2) {
  return _wrap_vtkConeSource_SetResolution(carg1, carg2);
}
int vtkConeSource_GetResolution(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetResolution(carg1);
}
void vtkConeSource_SetCenter(SwigObj * carg1, double carg2, double carg3, double carg4) {
  return _wrap_vtkConeSource_SetCenter(carg1, carg2, carg3, carg4);
}
double * vtkConeSource_GetCenter_pvtkConeSource(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetCenter_pvtkConeSource(carg1);
}
void vtkConeSource_GetCenter_pvtkConeSource_a3d(SwigObj * carg1, /*aaa*/ double * carg2) {
  return _wrap_vtkConeSource_GetCenter_pvtkConeSource_a3d(carg1, carg2);
}
void vtkConeSource_SetDirection(SwigObj * carg1, double carg2, double carg3, double carg4) {
  return _wrap_vtkConeSource_SetDirection(carg1, carg2, carg3, carg4);
}
double * vtkConeSource_GetDirection(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetDirection(carg1);
}
void vtkConeSource_SetAngle(SwigObj * carg1, double carg2) {
  return _wrap_vtkConeSource_SetAngle(carg1, carg2);
}
double vtkConeSource_GetAngle(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetAngle(carg1);
}
/*aaaaaa*/SwigObj * vtkConeSource_GetOutputPort(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetOutputPort(carg1);
}
/*aaaaaa*/SwigObj * vtkConeSource_NewInstance(SwigObj * carg1) {
  return _wrap_vtkConeSource_NewInstance(carg1);
}
bool vtkConeSource_GetDebug(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetDebug(carg1);
}
void vtkConeSource_SetDebug(SwigObj * carg1, bool carg2) {
  return _wrap_vtkConeSource_SetDebug(carg1, carg2);
}
const char * vtkConeSource_GetClassName(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetClassName(carg1);
}
int vtkConeSource_IsA(SwigObj * carg1, char const * carg2) {
  return _wrap_vtkConeSource_IsA(carg1, carg2);
}
void vtkConeSource_Print(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkConeSource_Print(carg1, carg2);
}
void vtkConeSource_Register(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkConeSource_Register(carg1, carg2);
}
void vtkConeSource_UnRegister(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkConeSource_UnRegister(carg1, carg2);
}
/*aaaaaa*/SwigObj * vtkRenderer_New() {
  return _wrap_vtkRenderer_New();
}
void vtkRenderer_Delete(SwigObj * carg1) {
  return _wrap_vtkRenderer_Delete(carg1);
}
void vtkRenderer_AddActor(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkRenderer_AddActor(carg1, carg2);
}
void vtkRenderer_SetBackground(SwigObj * carg1, double carg2, double carg3, double carg4) {
  return _wrap_vtkRenderer_SetBackground(carg1, carg2, carg3, carg4);
}
void vtkRenderer_SetBackground2(SwigObj * carg1, double carg2, double carg3, double carg4) {
  return _wrap_vtkRenderer_SetBackground2(carg1, carg2, carg3, carg4);
}
void vtkRenderer_SetGradientBackground(SwigObj * carg1, bool carg2) {
  return _wrap_vtkRenderer_SetGradientBackground(carg1, carg2);
}
/*aaaaaa*/SwigObj * vtkRenderWindow_New() {
  return _wrap_vtkRenderWindow_New();
}
void vtkRenderWindow_Delete(SwigObj * carg1) {
  return _wrap_vtkRenderWindow_Delete(carg1);
}
void vtkRenderWindow_AddRenderer(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkRenderWindow_AddRenderer(carg1, carg2);
}
void vtkRenderWindow_SetSize(SwigObj * carg1, int carg2, int carg3) {
  return _wrap_vtkRenderWindow_SetSize(carg1, carg2, carg3);
}
/*aaaaaa*/SwigObj * vtkRenderWindowInteractor_New() {
  return _wrap_vtkRenderWindowInteractor_New();
}
void vtkRenderWindowInteractor_Delete(SwigObj * carg1) {
  return _wrap_vtkRenderWindowInteractor_Delete(carg1);
}
void vtkRenderWindowInteractor_SetRenderWindow(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkRenderWindowInteractor_SetRenderWindow(carg1, carg2);
}
void vtkRenderWindowInteractor_Initialize(SwigObj * carg1) {
  return _wrap_vtkRenderWindowInteractor_Initialize(carg1);
}
void vtkRenderWindowInteractor_Start(SwigObj * carg1) {
  return _wrap_vtkRenderWindowInteractor_Start(carg1);
}
void vtkRenderWindowInteractor_SetInteractorStyle(vtkRenderWindowInteractor * carg1, SwigObj * carg2) {
  return _wrap_vtkRenderWindowInteractor_SetInteractorStyle(carg1, carg2);
}
/*aaaaaa*/SwigObj * vtkRenderWindowInteractor_GetInteractorStyle(vtkRenderWindowInteractor * carg1) {
  return _wrap_vtkRenderWindowInteractor_GetInteractorStyle(carg1);
}
/*aaaaaa*/SwigObj * vtkInteractorStyleTrackballCamera_New() {
  return _wrap_vtkInteractorStyleTrackballCamera_New();
}
void vtkInteractorStyleTrackballCamera_Delete(SwigObj * carg1) {
  return _wrap_vtkInteractorStyleTrackballCamera_Delete(carg1);
}
/*aaaaaa*/SwigObj * vtkBoxWidget_New() {
  return _wrap_vtkBoxWidget_New();
}
void vtkBoxWidget_Delete(SwigObj * carg1) {
  return _wrap_vtkBoxWidget_Delete(carg1);
}
void vtkBoxWidget_SetInteractor(vtkBoxWidget * carg1, SwigObj * carg2) {
  return _wrap_vtkBoxWidget_SetInteractor(carg1, carg2);
}
/*aaaaaa*/SwigObj * vtkBoxWidget_GetInteractor(vtkBoxWidget * carg1) {
  return _wrap_vtkBoxWidget_GetInteractor(carg1);
}
void vtkBoxWidget_PlaceWidget(SwigObj * carg1) {
  return _wrap_vtkBoxWidget_PlaceWidget(carg1);
}
void vtkBoxWidget_SetPlaceFactor(vtkBoxWidget * carg1, double carg2) {
  return _wrap_vtkBoxWidget_SetPlaceFactor(carg1, carg2);
}
double vtkBoxWidget_GetPlaceFactor(vtkBoxWidget * carg1) {
  return _wrap_vtkBoxWidget_GetPlaceFactor(carg1);
}
void vtkBoxWidget_SetProp3D(vtkBoxWidget * carg1, SwigObj * carg2) {
  return _wrap_vtkBoxWidget_SetProp3D(carg1, carg2);
}
/*aaaaaa*/SwigObj * vtkBoxWidget_GetProp3D(vtkBoxWidget * carg1) {
  return _wrap_vtkBoxWidget_GetProp3D(carg1);
}
void vtkBoxWidget_On(SwigObj * carg1) {
  return _wrap_vtkBoxWidget_On(carg1);
}
void vtkBoxWidget_Off(SwigObj * carg1) {
  return _wrap_vtkBoxWidget_Off(carg1);
}

