/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */
#include "vtk_proxy.h"

/*aaaaaa*/SwigObj * _wrap_vtkConeSource_New();
void _wrap_vtkConeSource_SetHeight(SwigObj * carg1, double carg2);
double _wrap_vtkConeSource_GetHeight(SwigObj * carg1);
void _wrap_vtkConeSource_SetRadius(SwigObj * carg1, double carg2);
double _wrap_vtkConeSource_GetRadius(SwigObj * carg1);
void _wrap_vtkConeSource_SetResolution(SwigObj * carg1, int carg2);
int _wrap_vtkConeSource_GetResolution(SwigObj * carg1);
void _wrap_vtkConeSource_SetCenter(SwigObj * carg1, double carg2, double carg3, double carg4);
double * _wrap_vtkConeSource_GetCenter_pvtkConeSource(SwigObj * carg1);
void _wrap_vtkConeSource_GetCenter_pvtkConeSource_a3d(SwigObj * carg1, /*aaa*/ double * carg2);
void _wrap_vtkConeSource_SetDirection(SwigObj * carg1, double carg2, double carg3, double carg4);
double * _wrap_vtkConeSource_GetDirection(SwigObj * carg1);
void _wrap_vtkConeSource_SetAngle(SwigObj * carg1, double carg2);
double _wrap_vtkConeSource_GetAngle(SwigObj * carg1);

/*aaaaaa*/SwigObj * vtkConeSource_New() {
  return _wrap_vtkConeSource_New();
}
void vtkConeSource_SetHeight(SwigObj * carg1, double carg2) {
  return _wrap_vtkConeSource_SetHeight(carg1, carg2);
}
double vtkConeSource_GetHeight(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetHeight(carg1);
}
void vtkConeSource_SetRadius(SwigObj * carg1, double carg2) {
  return _wrap_vtkConeSource_SetRadius(carg1, carg2);
}
double vtkConeSource_GetRadius(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetRadius(carg1);
}
void vtkConeSource_SetResolution(SwigObj * carg1, int carg2) {
  return _wrap_vtkConeSource_SetResolution(carg1, carg2);
}
int vtkConeSource_GetResolution(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetResolution(carg1);
}
void vtkConeSource_SetCenter(SwigObj * carg1, double carg2, double carg3, double carg4) {
  return _wrap_vtkConeSource_SetCenter(carg1, carg2, carg3, carg4);
}
double * vtkConeSource_GetCenter_pvtkConeSource(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetCenter_pvtkConeSource(carg1);
}
void vtkConeSource_GetCenter_pvtkConeSource_a3d(SwigObj * carg1, /*aaa*/ double * carg2) {
  return _wrap_vtkConeSource_GetCenter_pvtkConeSource_a3d(carg1, carg2);
}
void vtkConeSource_SetDirection(SwigObj * carg1, double carg2, double carg3, double carg4) {
  return _wrap_vtkConeSource_SetDirection(carg1, carg2, carg3, carg4);
}
double * vtkConeSource_GetDirection(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetDirection(carg1);
}
void vtkConeSource_SetAngle(SwigObj * carg1, double carg2) {
  return _wrap_vtkConeSource_SetAngle(carg1, carg2);
}
double vtkConeSource_GetAngle(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetAngle(carg1);
}

