/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */
#include "vtk_proxy.h"

/*aaaaaa*/SwigObj * _wrap_vtkConeSource_New();
void _wrap_vtkConeSource_Delete(SwigObj * carg1);
void _wrap_vtkConeSource_SetHeight(SwigObj * carg1, double carg2);
double _wrap_vtkConeSource_GetHeight(SwigObj * carg1);
void _wrap_vtkConeSource_SetRadius(SwigObj * carg1, double carg2);
double _wrap_vtkConeSource_GetRadius(SwigObj * carg1);
void _wrap_vtkConeSource_SetResolution(SwigObj * carg1, int carg2);
int _wrap_vtkConeSource_GetResolution(SwigObj * carg1);
void _wrap_vtkConeSource_SetCenter(SwigObj * carg1, double carg2, double carg3, double carg4);
double * _wrap_vtkConeSource_GetCenter(SwigObj * carg1);
void _wrap_vtkConeSource_GetCenterVec(SwigObj * carg1, /*aaa*/ double * carg2);
void _wrap_vtkConeSource_SetDirection(SwigObj * carg1, double carg2, double carg3, double carg4);
double * _wrap_vtkConeSource_GetDirection(SwigObj * carg1);
void _wrap_vtkConeSource_SetAngle(SwigObj * carg1, double carg2);
double _wrap_vtkConeSource_GetAngle(SwigObj * carg1);
/*aaaaaa*/SwigObj * _wrap_vtkRenderer_New();
void _wrap_vtkRenderer_Delete(SwigObj * carg1);
void _wrap_vtkRenderer_SetBackground(SwigObj * carg1, double carg2, double carg3, double carg4);
void _wrap_vtkRenderer_SetBackground2(SwigObj * carg1, double carg2, double carg3, double carg4);
void _wrap_vtkRenderer_SetGradientBackground(SwigObj * carg1, bool carg2);
/*aaaaaa*/SwigObj * _wrap_vtkRenderWindow_New();
void _wrap_vtkRenderWindow_Delete(SwigObj * carg1);
void _wrap_vtkRenderWindow_AddRenderer(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkRenderWindow_SetSize(SwigObj * carg1, int carg2, int carg3);
/*aaaaaa*/SwigObj * _wrap_vtkRenderWindowInteractor_New();
void _wrap_vtkRenderWindowInteractor_Delete(SwigObj * carg1);
void _wrap_vtkRenderWindowInteractor_SetRenderWindow(SwigObj * carg1, SwigObj * carg2);
void _wrap_vtkRenderWindowInteractor_Initialize(SwigObj * carg1);
void _wrap_vtkRenderWindowInteractor_Start(SwigObj * carg1);

/*aaaaaa*/SwigObj * vtkConeSource_New() {
  return _wrap_vtkConeSource_New();
}
void vtkConeSource_Delete(SwigObj * carg1) {
  return _wrap_vtkConeSource_Delete(carg1);
}
void vtkConeSource_SetHeight(SwigObj * carg1, double carg2) {
  return _wrap_vtkConeSource_SetHeight(carg1, carg2);
}
double vtkConeSource_GetHeight(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetHeight(carg1);
}
void vtkConeSource_SetRadius(SwigObj * carg1, double carg2) {
  return _wrap_vtkConeSource_SetRadius(carg1, carg2);
}
double vtkConeSource_GetRadius(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetRadius(carg1);
}
void vtkConeSource_SetResolution(SwigObj * carg1, int carg2) {
  return _wrap_vtkConeSource_SetResolution(carg1, carg2);
}
int vtkConeSource_GetResolution(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetResolution(carg1);
}
void vtkConeSource_SetCenter(SwigObj * carg1, double carg2, double carg3, double carg4) {
  return _wrap_vtkConeSource_SetCenter(carg1, carg2, carg3, carg4);
}
double * vtkConeSource_GetCenter(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetCenter(carg1);
}
void vtkConeSource_GetCenterVec(SwigObj * carg1, /*aaa*/ double * carg2) {
  return _wrap_vtkConeSource_GetCenterVec(carg1, carg2);
}
void vtkConeSource_SetDirection(SwigObj * carg1, double carg2, double carg3, double carg4) {
  return _wrap_vtkConeSource_SetDirection(carg1, carg2, carg3, carg4);
}
double * vtkConeSource_GetDirection(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetDirection(carg1);
}
void vtkConeSource_SetAngle(SwigObj * carg1, double carg2) {
  return _wrap_vtkConeSource_SetAngle(carg1, carg2);
}
double vtkConeSource_GetAngle(SwigObj * carg1) {
  return _wrap_vtkConeSource_GetAngle(carg1);
}
/*aaaaaa*/SwigObj * vtkRenderer_New() {
  return _wrap_vtkRenderer_New();
}
void vtkRenderer_Delete(SwigObj * carg1) {
  return _wrap_vtkRenderer_Delete(carg1);
}
void vtkRenderer_SetBackground(SwigObj * carg1, double carg2, double carg3, double carg4) {
  return _wrap_vtkRenderer_SetBackground(carg1, carg2, carg3, carg4);
}
void vtkRenderer_SetBackground2(SwigObj * carg1, double carg2, double carg3, double carg4) {
  return _wrap_vtkRenderer_SetBackground2(carg1, carg2, carg3, carg4);
}
void vtkRenderer_SetGradientBackground(SwigObj * carg1, bool carg2) {
  return _wrap_vtkRenderer_SetGradientBackground(carg1, carg2);
}
/*aaaaaa*/SwigObj * vtkRenderWindow_New() {
  return _wrap_vtkRenderWindow_New();
}
void vtkRenderWindow_Delete(SwigObj * carg1) {
  return _wrap_vtkRenderWindow_Delete(carg1);
}
void vtkRenderWindow_AddRenderer(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkRenderWindow_AddRenderer(carg1, carg2);
}
void vtkRenderWindow_SetSize(SwigObj * carg1, int carg2, int carg3) {
  return _wrap_vtkRenderWindow_SetSize(carg1, carg2, carg3);
}
/*aaaaaa*/SwigObj * vtkRenderWindowInteractor_New() {
  return _wrap_vtkRenderWindowInteractor_New();
}
void vtkRenderWindowInteractor_Delete(SwigObj * carg1) {
  return _wrap_vtkRenderWindowInteractor_Delete(carg1);
}
void vtkRenderWindowInteractor_SetRenderWindow(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_vtkRenderWindowInteractor_SetRenderWindow(carg1, carg2);
}
void vtkRenderWindowInteractor_Initialize(SwigObj * carg1) {
  return _wrap_vtkRenderWindowInteractor_Initialize(carg1);
}
void vtkRenderWindowInteractor_Start(SwigObj * carg1) {
  return _wrap_vtkRenderWindowInteractor_Start(carg1);
}

